name: "testing"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
              php:
                - 7.0
                - 7.1
                - 7.2
                - 7.3
                - 7.4
              composer-args: [ "" ]
              include:
                - php: 8.0
                  composer-args: --ignore-platform-reqs
            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-args }}

            - name: Tests
              run: composer test-coverage
